// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vczwhntxviloqrgetqkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjendobnR4dmlsb3FyZ2V0cWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzk5MDcsImV4cCI6MjA2MTcxNTkwN30.uv35zXVdnDv1-ENMF2BCNk3R72jVu1ttj274i4xgbxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);